### ISSUE TITLE
issues with compilation

### ISSUE THREAD

**Issue by mshpak76** [linsalrob/fastq-pair#18]
I am unable to run make3, so I followed the instructions suggested to another user who experienced a similar problem. However, when creating the /build directory and executing

    sudo gcc  ../*.c -o fastq_pair

I get the following error which I can't make sense of:

    /usr/bin/ld: /tmp/ccPYVGea.o: in function `main':
    test_gzip.c:(.text+0x0): multiple definition of `main'; /tmp/ccSZ6ste.o:main.c:(.text+0x7d): first defined here
    collect2: error: ld returned 1 exit status

Any suggestions on how to proceed?

**Comment by linsalrob** [comment]
Change the gcc command to 

```
gcc -std=gnu99  -o fastq_pair fastq_pair.c main.c  robstr.c is_gzipped.c
```

There are two files that contain a method with the signature `int main(int argc, char* argv[])` and so the compiler can't decide where to start. By explicitly naming the files, this problem is avoided.
