### ISSUE TITLE
Can't install it in Ubuntu 22

### ISSUE THREAD

**Issue by desmodus1984** [linsalrob/fastq-pair#19]
Hi I am trying to install it, and I got consistently the error:

cmake3 ../
Command 'cmake3' not found, did you mean:
  command 'cmake' from snap cmake (3.27.7)
  command 'cmake' from deb cmake (3.22.1-1ubuntu1.22.04.1)
See 'snap info <snapname>' for additional versions.

Could you suggest how to install it?

Thanks

**Comment by johned0** [comment]
If you have cmake v3.x installed you should be able to run just the cmake command, without the major version number
