### ISSUE TITLE
Pair mismatched when read name is close

### ISSUE THREAD

**Issue by Fatmice** [linsalrob/fastq-pair#2]
There is a read in R2 named 
NS500207:121:HTFVJAFXX:1:11111:13010:1958
Later there is another named
NS500207:121:HTFVJAFXX:1:11111:13010:19581

R1 only has a read named
NS500207:121:HTFVJAFXX:1:11111:13010:1958

This tool will mistakenly write into R1.paired.fq 
NS500207:121:HTFVJAFXX:1:11111:13010:1958
a second time thinking that such a pair existed.

This leads to mismatches in tools that require absolute name matching for read merging, such as usearch.

**Comment by linsalrob** [comment]
I have corrected the way that R1/R2 are detected and that will solve this problem. I have also added a new test data set.

**Comment by Fatmice** [comment]
Thank you.  I've tested on my own data set and seems good.
