### ISSUE TITLE
What would happen if line number cannot be exactly divided by four

### ISSUE THREAD

**Issue by wshuai294** [linsalrob/fastq-pair#20]
Thanks for the amazing tool.

I want to ask if the fastq file has much noise; some reads might contain less than four lines. Will the tool consider this situation?

Best,
Shuai

**Comment by linsalrob** [comment]
Hi Shuai

Unfortunately not at the moment. There are some multi-line fastq files but most tools don't support them any more, and they are unusual.

[Here are some alternative approaches that you can try](https://edwards.flinders.edu.au/sorting-and-paring-fastq-files/).
