### ISSUE TITLE
Output corrupted with gzipped reads

### ISSUE THREAD

**Issue by bsiranosian** [linsalrob/fastq-pair#6]
When I give two gzipped reads to fastq_pair, it seems to function normally. The output files are named with the .fq extension, but they're not a text file, nor a gzipped file. 

```
$ fastq_pair SAMPLE_1.fq.gz SAMPLE_2.fq.gz
Writing the paired reads to SAMPLE_1.fq.gz.paired.fq and SAMPLE_2.fq.gz.paired.fq.
Writing the single reads to SAMPLE_1.fq.gz.single.fq and SAMPLE_2.fq.gz.single.fq
Left paired: 11619              Right paired: 11619
Left single: 381534             Right single: 418985

$ file -i SAMPLE_1.fq.gz.paired.fq
SAMPLE_1.fq.gz.paired.fq: application/octet-stream; charset=binary

$ gzip -t SAMPLE_1.fq.gz.paired.fq
gzip: SAMPLE_1.fq.gz.paired.fq: not in gzip format
```

**Comment by bsiranosian** [comment]
Sorry, realized this was covered in the readme. Still, should not exit without an error if gzipped reads are given...

**Comment by linsalrob** [comment]
Agreed. This needs to be resolved. Its because we're using random access to the filestream that is not possible with gzipped files.
