### ISSUE TITLE
First read repeated with reads from SRA

### ISSUE THREAD

**Issue by bsiranosian** [linsalrob/fastq-pair#7]
I have a problem with reads downloaded from SRA. When the first read is present in the dataset, it gets repeated in the paired output. 

attaching two 20 line files as an example. 
[r1short.fq.txt](https://github.com/linsalrob/fastq-pair/files/3461463/r1short.fq.txt)
[r2short.fq.txt](https://github.com/linsalrob/fastq-pair/files/3461464/r2short.fq.txt)

These are the headers of the output for read 1: 
```
@SRR6913986.1 HISEQ:556:HCHYJBCXY:2:1101:3383:2114 length=301
@SRR6913986.1 HISEQ:556:HCHYJBCXY:2:1101:3383:2114 length=301
@SRR6913986.3 HISEQ:556:HCHYJBCXY:2:1101:3856:2081 length=301
@SRR6913986.4 HISEQ:556:HCHYJBCXY:2:1101:3919:2100 length=301
@SRR6913986.6 HISEQ:556:HCHYJBCXY:2:1101:4387:2166 length=301
```
and read 2 
```
@SRR6913986.1 HISEQ:556:HCHYJBCXY:2:1101:3383:2114 length=301
@SRR6913986.2 HISEQ:556:HCHYJBCXY:2:1101:3520:2051 length=301
@SRR6913986.3 HISEQ:556:HCHYJBCXY:2:1101:3856:2081 length=301
@SRR6913986.4 HISEQ:556:HCHYJBCXY:2:1101:3919:2100 length=301
@SRR6913986.6 HISEQ:556:HCHYJBCXY:2:1101:4387:2166 length=301
```

**Comment by linsalrob** [comment]
There is a problem with your IDs in r1short.fq and r2short.fq. Basically, the id's need to be in the format @SRR6913986.1.1 and @SRR6913986.1.2 to distinguish left and right reads (or @SRR6913986.1/1 and @SRR6913986.1/2). You have stripped out the .1 and .2 that indicates left and right reads from the IDs.

Unfortunately, there are a few different ways of denoting left and right reads, and fastq-dump only (currently) supports .1 & .2 or /1 & /2.

It may be helpful to download the dataset using [fastq-dump ](https://edwards.sdsu.edu/research/fastq-dump/) e.g. with this command:

```
fastq-dump --outdir fastq --gzip --skip-technical  --readids --read-filter pass --dumpbase --split-3 --clip SRR6913986
```

which will give you appropriately paired datasets with the correct IDs. For example, the first few reads have the following IDs:

```
@SRR6913986.1.1 HISEQ:556:HCHYJBCXY:2:1101:3383:2114 length=301
@SRR6913986.2.1 HISEQ:556:HCHYJBCXY:2:1101:3520:2051 length=301
@SRR6913986.3.1 HISEQ:556:HCHYJBCXY:2:1101:3856:2081 length=301
```

Notice how these have the .1 and .2 appended to the ID.

Rob

**Comment by bsiranosian** [comment]
Hi Rob, thanks for the reply. I had found your fastq-pair post in the past and was using that previously. I ended up having to strip out the readids for something else I was working on... so I'll add that flag back in for now!
